Migrate to Go modules
elyby/chrly pull request #33
Opened 2022-01-16 21:01 UTC by averyanalex

2022-01-18 17:33 UTC, erickskrauch requested changes

2022-01-18 17:33 UTC, erickskrauch commented on go.mod
> +	github.com/SermoDigital/jose v0.9.2-0.20161205224733-f6df55f235c2
Прежде здесь использовалась версия `1.1.0`.

2022-01-18 17:33 UTC, erickskrauch commented on go.mod
> +	github.com/stretchr/testify v1.7.0
Прежде использовалась версия `1.5.1`.

2022-01-18 17:43 UTC, averyanalex commented on go.mod
> +	github.com/stretchr/testify v1.7.0
Go с 1.5.1 не билдит - но sum entry. go mod tidy автоматом ставит 1.7.0
go test ./... OK
go test -v -race --tags redis -coverprofile=coverage.txt -covermode=atomic ./... OK

2022-01-18 17:47 UTC, averyanalex commented on go.mod
> +	github.com/SermoDigital/jose v0.9.2-0.20161205224733-f6df55f235c2
v1.1.0: go: github.com/SermoDigital/jose@v1.1.0: reading github.com/SermoDigital/jose/go.mod at revision v1.1.0: unknown revision v1.1.0
v1.1: /home/alex/projects/averyanalex/chrly/go.mod:6:2: no matching versions for query "v1.1"
1.1: автоматом ставит v0.9.2-0.20161205224733-f6df55f235c2
Все тесты OK

2022-01-18 19:09 UTC, averyanalex commented on go.mod
> +	github.com/SermoDigital/jose v0.9.2-0.20161205224733-f6df55f235c2
go get github.com/SermoDigital/jose@1.1
go get: added github.com/SermoDigital/jose v0.9.2-0.20161205224733-f6df55f235c2
1.1 = v0.9.2-0.20161205224733-f6df55f235c2

2022-01-24 11:04 UTC, erickskrauch approved these changes
Хорошо. Смержим вместе с #34 и #35.

2022-01-24 11:05 UTC, averyanalex commented
Пока без #35

2022-01-24 11:18 UTC, erickskrauch commented
> Пока без #35

Увы, но без не получится. Или тогда нужно править [.travis.yml](https://github.com/elyby/chrly/blob/master/.travis.yml) под сборку на gomod, или ждать полноценного переезда с завершением в #35. Иначе же репозиторий просто повиснет в переходном состоянии, когда gomod как бы есть, а процессов сборки под него как бы нет.

2023-12-13 00:58 UTC, erickskrauch commented
Fixed with https://github.com/elyby/chrly/commit/6accffed455fc90c6c107e487be1b60f21a761e4.

2023-12-13 00:58 UTC, closed without merging