Update Dockerfile
elyby/chrly pull request #34
Opened 2022-01-16 21:04 UTC by averyanalex

Docker will build chrly, then build alpine-based small image

2022-01-18 17:42 UTC, erickskrauch requested changes

2022-01-18 17:42 UTC, erickskrauch commented on Dockerfile
> +RUN go build -v -o chrly
Не всё так просто :) Нужно и зависимости установить, и версию прокинуть, и флаги для статической сборки прописать. Посмотри, как собирается бинарник в файле `.travis.yml`. Если загонять эту сборку в докер, то нужно повторить такой же итоговый файл.

2022-01-18 17:42 UTC, erickskrauch commented on Dockerfile
> +COPY . .
Как-то всё слишком спресованно выглядит. Добавь пустую строку после `FROM` и перед `RUN`. Тогда будет чутка почитаемее.

2022-01-18 18:12 UTC, averyanalex commented on Dockerfile
> +COPY . .
Добавил (и парочку комментариев)

2022-01-18 18:12 UTC, averyanalex commented
To build dev version (profiling tag)
docker build --build-arg BUILD_TYPE=dev -t chrly .

2022-01-24 11:33 UTC, erickskrauch approved these changes
Всё отлично. Смержим вместе с #33 и #35.

2023-12-13 00:59 UTC, erickskrauch commented
Fixed with https://github.com/elyby/chrly/commit/6accffed455fc90c6c107e487be1b60f21a761e4.

2023-12-13 00:59 UTC, closed without merging